name: CV Sitesini Otomatik Guncelle

# TETİKLEYİCİ: Ne zaman çalışsın?
on:
  push:
    branches:
      - main
    paths:
      - 'index.html' # Sadece HTML değişirse çalış, boşuna yorulma.

# GÖREVLER: Neler yapsın?
jobs:
  deploy-site:
    runs-on: ubuntu-latest # GitHub'ın sanal Linux bilgisayarında çalış
    steps:
      # 1. Adım: Kodları Çek
      - name: Kodlari GitHubdan Al
        uses: actions/checkout@v3

      # 2. Adım: AWS'ye Giriş Yap (Kasadan şifreleri alarak)
      - name: AWSye Giris Yap
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Adım: Dosyayı S3'e Yükle
      - name: Dosyayi S3e Yukle
        run: |
          aws s3 cp index.html s3://${{ secrets.S3_BUCKET_NAME }}/

      # 4. Adım: CloudFront Önbelleğini Temizle (Güncel görünsün)
      - name: CloudFrontu Temizle
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"